src/Entity/TrassirNvr.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrassirNvrRepository")
 * @UniqueEntity(
 *     fields={"Ip"},
 *     errorPath="Ip",
 *     message="Ip address already exists"
 *    )
 */
class TrassirNvr
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     * @Assert\Ip
     */
    private $Ip;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $guid;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastHealthAndDataCollectedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Facility", fetch="EAGER")
     */
    private $facility;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIp(): ?string
    {
        return $this->Ip;
    }

    public function setIp(string $Ip): self
    {
        $this->Ip = $Ip;

        return $this;
    }

    public function getGuid(): ?string
    {
        return $this->guid;
    }

    public function setGuid(?string $guid): self
    {
        $this->guid = $guid;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastHealthAndDataCollectedAt(): ?\DateTimeInterface
    {
        return $this->lastHealthAndDataCollectedAt;
    }

    public function setLastHealthAndDataCollectedAt(?\DateTimeInterface $lastHealthAndDataCollectedAt): self
    {
        $this->lastHealthAndDataCollectedAt = $lastHealthAndDataCollectedAt;

        return $this;
    }

    public function getFacility(): ?Facility
    {
        return $this->facility;
    }

    public function setFacility(?Facility $facility): self
    {
        $this->facility = $facility;

        return $this;
    }
}

src/Controller/Facility/FacilityController.php
<?php


namespace App\Controller\Facility;


use App\Controller\Facility\Forms\AddFacilityForm;
use App\Controller\Facility\Forms\EditFacilityForm;
use App\Controller\Facility\Forms\testForm;
use App\Entity\AlarmSystem;
use App\Entity\Facility;
use App\Entity\Safe;
use App\Entity\SecurityDevice;
use App\Entity\TrassirNvr;
use App\Entity\TrassirNvrData;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FacilityController extends AbstractController
{
    /**
     * @Route("/facilitylist", name="facilitylist")
     */
    public function facilityList(Request $request, EntityManagerInterface $em)
    {
        $this->denyAccessUnlessGranted('ROLE_FACILITY_LIST');
        $facilityRepo = $this->getDoctrine()->getRepository(Facility::class);
        $facilityList = $facilityRepo->findBy([],
            [
                'country' => 'ASC',
                'city' => 'ASC',
                'street' => 'ASC',
                'house' => 'ASC',
            ]);

        $trassirNvrRepo = $this->getDoctrine()->getRepository(TrassirNvr::class);
        $safesRepo = $this->getDoctrine()->getRepository(Safe::class);
        $alarmSystems = $this->getDoctrine()->getRepository(AlarmSystem::class);

        $nvrCount = [];
        foreach ($facilityList as $facility) {
            $nvrCount[$facility->getId()] = count($trassirNvrRepo->findBy(['facility' => $facility]));
            $nvrCount[$facility->getId()] += count($safesRepo->findBy(['facility' => $facility]));
            $nvrCount[$facility->getId()] += count($alarmSystems->findBy(['facility' => $facility]));
        }

        $addFacilityForm = $this->createForm(AddFacilityForm::class, new Facility());
        $addFacilityForm->handleRequest($request);
        if ($addFacilityForm->isSubmitted()) {
            /** @var $newFacility Facility */
            $newFacility = $addFacilityForm->getData();
            $formData = $request->request->get('add_facility_form');

            $isDuplicated = $facilityRepo->findBy([
                'country' => $formData['Country'],
                'city' => $formData['City'],
                'street' => $formData['Street'],
                'house' => $formData['House'],
            ]);

            $isDuplicatedLmcode = $facilityRepo->findBy([
                'lmcode' => $formData['lmcode'],

            ]);

            if (!$isDuplicated && !$isDuplicatedLmcode) {
                if ($newFacility->getCity() === null) {
                    $newFacility->setCity(trim($formData['City']));
                    $newFacility->setRegion(trim($formData['Region']));
                };

                if (!$newFacility->getName()) {
                    $newFacility->setName($newFacility->getCity() . ' ' . $newFacility->getStreet());
                }

                $em->persist($newFacility);
                $em->flush();

                return $this->redirectToRoute('facilitylist');
            }



        }


        return $this->render('facility/facilityList.html.twig', [
            'facilities' => $facilityList,
            'form' => $addFacilityForm->createView(),
            'nvrCount' => $nvrCount,
        ]);
    }

    /**
     * @Route ("/facility/edit/{id}", name="editFacility")
     */
    public function editFacility(EntityManagerInterface $em, Request $request, $id)
    {
        $this->denyAccessUnlessGranted('ROLE_FACILITY_EDIT');
        $facilityRepo = $this->getDoctrine()->getRepository(Facility::class);
        $facilityToEdit = $facilityRepo->find($id);


        $editFacilityForm = $this->createForm(EditFacilityForm::class, $facilityToEdit);
        $editFacilityForm->handleRequest($request);
        if ($editFacilityForm->isSubmitted() && $editFacilityForm->isValid()) {

            /** @var Facility $data */
            $data = $editFacilityForm->getData();

            $facilityToEdit->setName($data->getName());
            $facilityToEdit->setPostCode($data->getPostCode());
            $facilityToEdit->setStreetType($data->getStreetType());
            $facilityToEdit->setStreet($data->getStreet());
            $facilityToEdit->setHouse($data->getHouse());
            $facilityToEdit->setBuildingType($data->getBuildingType());
            $facilityToEdit->setBuilding($data->getBuilding());
            $facilityToEdit->setRoom($data->getRoom());

            $facilityToEdit->setLat($data->getLat());
            $facilityToEdit->setLon($data->getLon());


            $em->persist($facilityToEdit);
            $em->flush();
            //return $this->redirectToRoute('facilitylist');
        }

        return $this->render('facility/editFacility.html.twig', [
            'editFacilityForm' => $editFacilityForm->createView(),
            'facility' => $facilityToEdit,
        ]);
    }

    /**
     * @Route ("/facility/delete/{id}", name="deleteFacility")
     */
    public function deleteFacility(EntityManagerInterface $em, $id)
    {
        $this->denyAccessUnlessGranted('ROLE_FACILITY_DELETE');
        $facilityRepo = $this->getDoctrine()->getRepository(Facility::class);
        $facilityToDelete = $facilityRepo->find($id);


        if ($facilityToDelete) {
            $em->remove($facilityToDelete);
            $em->flush();
        }

        return $this->redirectToRoute('facilitylist');
    }

    /**
     * @Route("/getcities/{country}", name="getCities")
     */
    public function getCities($country = null)
    {
        if ($country == 'RU') {
            $cities = Facility::getRussianCities();
        } else if ($country == 'BY') {
            $cities = Facility::getByCities();
        }
        return new JsonResponse($cities);
    }

    /**
     * @Route("/facilityPassport/{id}", name = "facilityPassport")
     */
    public function facilityPassport($id)
    {
        $this->denyAccessUnlessGranted('ROLE_FACILITY');
        $facilityRepo = $this->getDoctrine()->getRepository(Facility::class);
        $facilityToShow = $facilityRepo->find($id);

        $securityDeviceRepo = $this->getDoctrine()->getRepository(SecurityDevice::class);
        $safeRepo = $this->getDoctrine()->getRepository(Safe::class);
        $trassirNvrRepo = $this->getDoctrine()->getRepository(TrassirNvr::class);

        $trassirNvrList = $trassirNvrRepo->findBy(['facility' => $facilityToShow]);

        $trassirDataRepo = $this->getDoctrine()->getRepository(TrassirNvrData::class);
        $trassirHealth = [];
        foreach ($trassirNvrList as $trassirNvr) {
            $trassirHealth[$trassirNvr->getId()] = $trassirDataRepo->findOneBy(['trassirNvrId' => $trassirNvr->getId()], ['dateTime' => 'DESC']);
        }

        return $this->render('facility/facilityPassport.html.twig', [
            'facility' => $facilityToShow,
            'securityDevices' => $securityDeviceRepo->findBy(['facility' => $facilityToShow]),
            'safes' => $safeRepo->findBy(['facility' => $facilityToShow]),
            'trassirNvr' => $trassirNvrList,
            'trassirNvrHealth' => $trassirHealth,
        ]);
    }

    /**
     * @Route("/setCoordinates/{id}/{lat}/{lon}" , name ="setCoordinates")
     */
    public function setCoordinates(EntityManagerInterface $entityManager, $id=null, $lat=null, $lon=null)
    {
        $this->denyAccessUnlessGranted('ROLE_FACILITY');
        if($id!=null && $lat!=null && $lon != null) {
            $facilityRepo = $this->getDoctrine()->getRepository(Facility::class);
            /**@var $facility Facility */
            $facility = $facilityRepo->find($id);

            $facility->setLat($lat);
            $facility->setLon($lon);

            $entityManager->persist($facility);
            $entityManager->flush();
        }


        return new JsonResponse('done');
    }

}

src/Controller/Facility/Forms/AddFacilityForm.php
<?php


namespace App\Controller\Facility\Forms;


use App\Entity\Facility;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddFacilityForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('Name', TextType::class, [
                'required' => false,
                'label' => 'Имя',
            ])
            ->add('PostCode', TextType::class, [
                'required' => false,
                'label' => 'Индекс',
            ])
            ->add('lmcode', TextType::class, [
                'required' => false,
                'label' => 'Lme код',
            ])
            ->add('facilityType', ChoiceType::class, [
                'choices' => Facility::getFacilityTypes(),
                'label' => 'Тип подразделения',
                'required' => false,
            ])
            ->add('Country', ChoiceType::class, [
                'choices' => Facility::COUNTRIES,
                'label' => 'Страна',
                'required' => false,
            ])
            ->add('Region', TextType::class, [
                'required' => true,
                'label' => 'Область',

                'attr' =>
                    [
                    'readonly'=>true,
                ]
            ])
            ->add(
                'City', ChoiceType::class, [
                    'required' => false,
                    'label' => 'Город',
                    'choices' => []
                ])
            ->add('StreetType', ChoiceType::class, [
                'choices' => array_flip(Facility::getStreetTypes()),
                'label' => 'Тип улицы',
                'required' => true,
            ])
            ->add('Street', TextType::class, [
                'required' => true,
                'label' => 'Название улицы',
            ])
            ->add('House', TextType::class, [
                'required' => true,
                'label' => 'Номер дома',
            ])
            ->add('BuildingType', ChoiceType::class, [
                'required' => false,
                'label' => 'Тип строения',
                'choices' => array_flip(Facility::getBuildingTypes())
            ])
            ->add('Building', TextType::class, [
                'required' => false,
                'label' => 'Номер строения',
            ])
            ->add('Room', TextType::class, [
                'required' => false,
                'label' => 'Номер помещения',
            ])
            ->add('Submit', SubmitType::class);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Facility::class,
        ]);
    }

}

src/Controller/Facility/Forms/EditFacilityForm.php
<?php


namespace App\Controller\Facility\Forms;


use App\Entity\Facility;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EditFacilityForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('Name', TextType::class, [
                'required' => false,
                'label' => 'Имя',
            ])
            ->add('PostCode', TextType::class, [
                'required' => false,
                'label' => 'Индекс',
            ])
            ->add('lmcode', TextType::class, [
                'required' => false,
                'label' => 'Lme код',
            ])
            ->add('facilityType', ChoiceType::class, [
                'choices' => Facility::getFacilityTypes(),
                'label' => 'Тип подразделения',
                'required' => false,
            ])
            ->add('StreetType', ChoiceType::class, [
                'choices' => array_flip(Facility::getStreetTypes()),
                'label' => 'Тип улицы',
                'required' => true,
                'attr' => array('style' => 'width: 150px')
            ])
            ->add('Street', TextType::class, [
                'required' => true,
                'label' => 'Улица',
                'attr' => array('class' => 'text-capitalize'),
            ])
            ->add('House', TextType::class, [
                'required' => true,
                'label' => 'Дом',
            ])
            ->add('BuildingType', ChoiceType::class, [
                'required' => false,
                'label' => 'Тип строения',
                'choices' => array_flip(Facility::getBuildingTypes())
            ])
            ->add('Building', TextType::class, [
                'required' => false,
                'label' => 'Строение',
            ])
            ->add('Room', TextType::class, [
                'required' => false,
                'label' => 'Помещение',
            ])
            ->add('Lat', TextType::class, [
                'required' => false,
                'label' => 'Latitude',
            ])
            ->add('Lon', TextType::class, [
                'required' => false,
                'label' => 'Longitude',
            ])
            ->add('Submit', SubmitType::class);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Facility::class,
        ]);
    }

}

templates/facility/editFacility.html.twig
{% extends 'home.html.twig' %}


{% block main %}

    <div class="row">
        <div class="col text-center">
            <h2>Edit Facility </h2>
        </div>
    </div>
    <div class="row">
        <div class="col bg-light">
            {% form_theme editFacilityForm 'bootstrap_4_horizontal_layout.html.twig' %}
            {{ form_start(editFacilityForm) }}
            {{ form_widget(editFacilityForm) }}
            <a href="{{ path('facilitylist') }}" class="btn btn-danger">Cancel</a>
            {{ form_end(editFacilityForm) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a id="refreshCoordinatesButton" href=""
               class="btn btn-success">Refresh Coordinates</a>
        </div>
    </div>
{% endblock %}


{% block javascriptsAfterBody %}
    {{ parent() }}

    <script>

        $("#refreshCoordinatesButton").click(function (e) {
            e.preventDefault();
            $('#edit_facility_form_Lat').val('....');
            $('#edit_facility_form_Lon').val('....');
            url = 'https://nominatim.openstreetmap.org/search?city={{ facility.city }}&street={{ facility.street }}&housenumber{{ facility.house }}&format=json&limit=1';
            $.ajax({
                url: url,
                success: function (data) {
                    if (data.length !== 0) {
                        console.log(data);
                        $lat = data[0]['lat'];
                        $lon = data[0]['lon'];
                    } else {
                        $lat = 'invalid address';
                        $lon = 'invalid address';
                    }
                    console.log($lat, $lon);
                    setCoordinates($lat, $lon);
                    console.log('ready to show');
                }
            });

        });


        function setCoordinates(lat, lon) {

            var path = '{{path('setCoordinates')}}';
            var url = path+'/{{ facility.id }}/' + lat + '/' + lon;
            console.log(url);

            $.ajax({
                method: "GET",
                url: url

            }).done(function (data) {
            });

            $('#edit_facility_form_Lat').val(lat);
            $('#edit_facility_form_Lon').val(lon);
        }
    </script>
{% endblock %}

templates/facility/facilityList.html.twig
{% extends 'home.html.twig' %}

{% block javascriptsBeforeBody %}
    {{ parent() }}

    <script type='text/javascript'
            src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AtrbFcv5kIq0_lr7oP2X9gCjolUGnrCC7zmicDR8cDymFpqV5Pm0JvGU0joAa3I3'
            async defer></script>

{% endblock %}
{% block main %}
    <div class="row">
        <div class="col">

        </div>
    </div>
    <div class="row m-2">
        <div class="col">
            <div id='myMap' style='width: 100%; height: 600px;'></div>
        </div>
    </div>
    {% if is_granted('ROLE_NVR_ADD') %}
        <div class="row bg-light p-2">
            <div class="col">
                {% form_theme form 'bootstrap_4_layout.html.twig' %}
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <div class="row">
                    <div class="col">
                        {{ form_row(form.Name) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.PostCode) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.lmcode) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.facilityType) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.Country) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.Region) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.City) }}
                    </div>
                    <div class="col"></div>

                </div>
                <div class="row">

                    <div class="col">
                        {{ form_row(form.StreetType) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.Street) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.House) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.BuildingType) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.Building) }}
                    </div>
                    <div class="col">
                        {{ form_row(form.Room) }}
                    </div>

                </div>
                <div class="row">
                    <div class="col">
                        {{ form_row(form.Submit, { 'label': 'Add new' }) }}
                    </div>
                    <div class="col"></div>
                    <div class="col"></div>
                </div>

                {{ form_end(form) }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col">

            <table class="table table-striped table-bordered mt-4">
                <thead>
                <tr class="">
                    <th class="tr_fixed">
                        #
                    </th>
                    <th class="tr_fixed">
                        Name
                    </th>
                    <th class="tr_fixed">
                        Type
                    </th>
                    <th class="tr_fixed">
                        Lmcode
                    </th>
                    <th class="tr_fixed">
                        Address
                    </th>
                    <th class="tr_fixed">
                        Actions
                    </th>
                    <th class="tr_fixed">
                        GPS
                    </th>
                </tr>
                </thead>
                <tbody class="pt-5">
                {% for facility in facilities %}
                    <tr>
                        <td>
                            <a href="{{ path('facilityPassport', {id: facility.id}) }}">
                                {{ loop.index }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ path('facilityPassport', {id: facility.id}) }}">
                                {{ facility.name }}
                            </a>
                        </td>
                        <td>{{ facility.facilityType }}</td>
                        <td>{{ facility.lmcode }}</td>
                        <td>{{ facility.address }}</td>
                        <td>
                            <a href="/facility/edit/{{ facility.id }}" class="btn btn-sm"><img
                                        alt="edit"
                                        width="20px"
                                        src="{{ asset('img/edit.png') }}">
                            </a>

                            {% if nvrCount[facility.id]==0 %}
                                <a href="#" data-href="/facility/delete/{{ facility.id }}" data-toggle="modal"
                                   data-target="#confirm-delete" class="btn btn-sm delete-type">
                                    <img alt="delete" width="20px" src="{{ asset('img/cancel.png') }}">
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if facility.lat is not null and facility.lat != 'error' and facility.lat != 'invalid address' %}
                                <img alt="gps" width="20px" src="{{ asset('img/target_32.png') }}">
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                {% include 'include/deleteConfirmationModal.html.twig' %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}


{% block javascriptsAfterBody %}
    {{ parent() }}

    <script>
        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        });

        $('#add_facility_form_Region').prop("readonly", true);

        $('#add_facility_form_Country').on('change', function (data) {
            var optionSelected = $(this).find("option:selected");
            var textSelected = optionSelected.text();

            var path = '{{ path('getCities') }}';
            path = path + '/' + textSelected;
            $.ajax({
                method: "POST",
                url: path,

            }).done(function (data) {
                $('#add_facility_form_City').empty();
                $.each(data, function (val, text) {
                    $('#add_facility_form_City').append(
                        $('<option></option>').val(text['city']).html(text['city'] + ' регион: ' + text['region'])
                    );
                });
            })
        });

        $('#add_facility_form_City').on('change', function (data) {
            var region = $(this).children("option:selected").val();
            region = $(this).children("option:selected").html();

            var regionStartPostition = region.indexOf('регион') + 8;
            var regionToOutput = region.slice(regionStartPostition);

            $("#add_facility_form_Region").val(regionToOutput);
        });


    </script>

    <script>
            var map, clusterLayer;
            function GetMap() {
                map = new Microsoft.Maps.Map('#myMap', {
                    zoom: 3,
                });

                //Create an infobox at the center of the map but don't show it.
                infobox = new Microsoft.Maps.Infobox(map.getCenter(), {
                    visible: false
                });
                //Assign the infobox to a map instance.
                infobox.setMap(map);

                Microsoft.Maps.loadModule("Microsoft.Maps.Clustering", function () {
                    var pins = [];

                    {% for facility in facilities %}
                        {% if facility.lon != 'error' and facility.lon is not null %}
                            var pin = new Microsoft.Maps.Pushpin(new Microsoft.Maps.Location({{ facility.lat }}, {{ facility.lon }}));

                            pin.metadata = {
                                description: '{{ facility.address }}',
                            };
                            Microsoft.Maps.Events.addHandler(pin, 'click', pushpinClicked);
                            pins.push(pin);
                        {% endif %}
                    {% endfor %}

                    clusterLayer = new Microsoft.Maps.ClusterLayer(pins);
                    map.layers.insert(clusterLayer);
                });
            }


            function pushpinClicked(e) {
                //Make sure the infobox has metadata to display.
                if (e.target.metadata) {
                    //Set the infobox options with the metadata of the pushpin.
                    infobox.setOptions({
                        location: e.target.getLocation(),
                        title: e.target.metadata.title,
                        description: e.target.metadata.description,
                        visible: true
                    });
                }
            }

    </script>

{% endblock %}

templates/facility/facilityPassport.html.twig
{% extends 'home.html.twig' %}

{% block main %}
    <div class="row text-center">
        <div class="col">
            <h1>{{ facility.name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <b>Адрес: {{ facility.address }}</b>
        </div>
    </div>
    <table class="table table-striped mt-3">
        <thead>
        <tr>
            <th>Параметр</th>
            <th>Состояние</th>
        </tr>
        </thead>
        <tbody>
        {% if safes|length >0 %}
            {% for safe in safes %}
                <tr>
                    <td>
                        Сейф: {{ safe.equipment.make }} {{ safe.equipment.model }} Серийный
                        номер: {{ safe.serial }}
                    </td>
                    <td>
                        {% if safe.status !="OK" %}
                            <img src="{{ asset('img/cancel.png') }}"> {{ safe.comment }}
                        {% else %}
                            <img src="{{ asset('img/done.png') }}"
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td>Сейф отсутствует</td>
                <td><img src="{{ asset('img/cancel.png') }}"></td>
            </tr>
        {% endif %}
        {% if trassirNvr|length >0 %}
            {% for nvr in trassirNvr %}
                <tr>
                    <td>
                        Trassir: {{ nvr.ip }} {{ nvr.name?? "" }}
                    </td>
                    <td>
                        {% if trassirNvrHealth[nvr.id].health is defined
                            and (trassirNvrHealth[nvr.id].health['network'] is defined
                            and trassirNvrHealth[nvr.id].health['network']==1) %}
                            {% set online = true %}
                        {% else %}
                            {% set online = false %}
                        {% endif %}
                    <img src="{{ online?asset('img/done.png'):asset('img/cancel.png') }}"
                             alt="Online status image">
                    </td>
                </tr>

                {% if trassirNvrHealth[nvr.id].objects.UserNames is defined and trassirNvrHealth[nvr.id].objects.UserNames|length>0 %}
                    <tr><td colspan="3">Users </td></tr>
                    {% for user in  trassirNvrHealth[nvr.id].objects.UserNames %}
                        <tr><td colspan="3" class="text-center"> {{ user }} </td></tr>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% else %}
            <tr>
                <td>Trassir отсутствует</td>
                <td><img src="{{ asset('img/cancel.png') }}"></td>
            </tr>
        {% endif %}

        </tbody>
    </table>


    <table class="table table-striped mt-3">
        <thead>
        <tr><th class="text-center thead-light" colspan="5">Размещенное обрудование</th></tr>
        <tr>
            <th>#</th>
            <th>Тип</th>
            <th>Марка</th>
            <th>Модель</th>
            <th>Серийный номер</th>
        </tr>
        </thead>
        <tbody>
        {% for device in securityDevices %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ device.equipment.type }}</td>
                <td>{{ device.equipment.make }}</td>
                <td>{{ device.equipment.model }}</td>
                <td>{{ device.serial }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}