BB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('trassir/', include('trassir.urls'))
]

trassir/urls.py
from django.urls import path, include
from . import views

app_name = 'trassir'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),\
    path("<int:nvr_id>/get_health/", views.get_health, name="get_health"),

]

trassir/models.py
import datetime

from django.db import models
import json, requests
import logging

# Logging configuration
py_logger = logging.getLogger(__name__)
py_logger.setLevel(logging.DEBUG)
py_handler = logging.FileHandler(f"{__name__}.log", mode='w')
py_formatter = logging.Formatter("%(name)s %(asctime)s %(levelname)s %(message)s")
py_handler.setFormatter(py_formatter)
py_logger.addHandler(py_handler)


# Create your models here.

class NVR(models.Model):
    # ip = models.CharField(max_length=100, unique=True) TODO unique after testing
    ip = models.CharField(max_length=100)
    port = models.IntegerField(default=80)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    sdk_password = models.CharField(max_length=100)
    name = models.CharField(max_length=200, editable=False)

    def __str__(self):
        return self.name + '(' + self.ip + ')'

    @staticmethod
    def make_request(command, username=None, password=None, sdk_password=None, session_id=None, ip='127.0.0.1',
                     port='8080'):
        request_string = f'https://{ip}:{port}/{command}'
        if session_id:
            request_string += '?sid=' + session_id
        elif sdk_password:
            request_string += '?password=' + sdk_password
        elif username and password:
            request_string += '?username=' + username + '&password=' + password
        else:
            raise Exception('please provide session')
        py_logger.debug('Trying request: ' + request_string)

        try:
            r = requests.get(request_string, verify=False, timeout=3)
            py_logger.debug('Response status_code = ' + str(r.status_code))
            py_logger.debug(r.text)

            if r.status_code == 200:
                return json.loads(r.text)

        except Exception as ex:
            py_logger.warning('Connection Error, ip=' + ip)
            py_logger.warning(ex)
            # raise Exception('ConnectionError')
            return 'error'

    def get_health(self):
        health = NVR.make_request(command='health', username=self.username,
                                  password=self.password,
                                  sdk_password=self.sdk_password,
                                  ip=str(self.ip))
        return health

    @staticmethod
    def get_health_keys():
        health_keys = ['disks', 'database', 'channels_total', 'channels_online', 'uptime', 'cpu_load', 'network',
                       'automation',
                       'disks_stat_main_days', 'disks_stat_priv_days', 'disks_stat_subs_days']
        return health_keys

    def get_last_health(self):
        try:
            result = json.loads(Health.objects.filter(server=self).order_by('-collected_at')[0].health.replace("'", '"'))
        # print(result)
        except IndexError:
            return False
        return result


class Health(models.Model):
    server = models.ForeignKey(NVR, on_delete=models.CASCADE)
    health = models.TextField()
    collected_at = models.DateTimeField()

    def __str__(self):
        return self.server.ip + str(self.collected_at)

trassir/views.py
import datetime

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import NVR, Health
import json


# Create your views here.

class IndexView(generic.ListView):
    model = NVR


class DetailView(generic.DetailView):
    model = NVR


def get_health(request, nvr_id):
    health = Health(server=NVR.objects.get(pk=nvr_id))
    health.health = json.dumps(NVR.objects.get(pk=nvr_id).get_health())
    health.collected_at = datetime.datetime.now()
    health.save()

    return HttpResponseRedirect(reverse("trassir:index"))

trassir/templates/trassir/NVR_detail.html
{% extends 'trassir/index.html' %}

{% block body %}
    <div class="row">
        <div class="col bg-secondary">
            some data about {{ nvr.name }} server
        </div>
    </div>

    <div class="row">
        <div class="col bg-secondary">
            {{ nvr.ip }}
        </div>
    </div>

    <table class="table table-striped">
        {% for health_data in nvr.health_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ health_data.health }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

trassir/templates/trassir/NVR_list.html
{% extends 'trassir/index.html' %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>SERVERS</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        IP
                    </th>

                    <th>
                        Refresh
                    </th>
                    {% for key in nvr_list.first.get_health_keys %}
                        <th>{{ key }}</th>
                    {% endfor %}
                </tr>
                {% for NVR in nvr_list %}
                    <tr>
                        <td>{{ forloop.counter }}
                        <td><a href="{% url 'trassir:detail' NVR.id %}">{{ NVR }}</a></td>
                        <td>{{ NVR.ip }}</td>
                        <td><a href="{% url 'trassir:get_health' NVR.id %}">+</a></td>
                        {% if NVR.get_last_health.items %}
                            {% for key, value in NVR.get_last_health.items %}
                                <td>{{ value }}</td>
                            {% endfor %}
                        {% elif NVR.get_last_health %}
                            <td>{{ NVR.get_last_health }}</td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}\

trassir/templates/trassir/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'trassir/bootstrap/css/bootstrap.css' %}"></link>
    <script src="{% static 'trassir/bootstrap/js/bootstrap.js' %}"></script>
    <title>Title</title>
</head>
<body>
<div class="container">
    {% block body %}

    {% endblock %}
</div>
</body>
</html>